sudo: true
language: python
matrix:
  include:
    - python: '3.6'
      env: DEPLOY_DOCKER_IMAGE=true
services:
  - mysql
  - redis-server
  - docker
install:
  - pip install flake8
  - pip install -r requirements.txt
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('squash') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade --user=root --password=squash
  - sudo service mysql restart
  - mysql --user=root --password=squash -e 'CREATE DATABASE squash_test;'
script:
  - make test
  - make travis-build
after_success:
  - make travis-docker-deploy
env:
  global:
    - DEPLOY_DOCKER_IMAGE=false  # disable docker push in regular test matrix
    # travis encrypt "DOCKER_USERNAME=... DOCKER_PASSWORD=..."
    - secure: "kFV7gMfeb1cLp+bL1H8lKj1xyqNj0T4wCVoBj8tIP2SemCjZer95qs1fUBJxooF17BeR/VJ9zebpm5nti6OS9L96T3FVMsGmbBRKK/qQ9pGQll7Y5lUFlFCOYnGvdis487aKiwbVl1DHHJX72N1MoZS2SHAQcBB2jne+NTtFwF/Ts223Yl7cBRTtva8ty03sHAwHdWrbYo3klaSBkHFCUCgUdFKPasJ47wt+pwN7s/NZo/UV4nC8f0SSH+ZelHDBADJOKgCcABAy06b7C8jh/KrvjFipu6zOtkjjekx+8zw7yKHqfWcYiis3oniItCoUuuFInVuFIy1OBgb5sxtnFmaD1EMzMvathaPLz+FTLxWxuzjydKvt2HrTBpLzwwyRD8sNnL92dUSZtndn55oVOpCtGr228hLRWr6djJ0Ip6f4UJ/x+xjGooZrqLz0WhpaGL1qCX3ry6ctyJETQHFZotZyPkbZ557ZRAEBjrZ8WCirNqwd1tUm0T8mxV7ghNhMWuu3HXJ/ZP9jLld719OPlnGJGtdf8HtEKZjFNHhJkZDTOMNcwT3xqQTusS2AKR9RJtzOwt95kq6m7VzaRuy667tuvzM+PRnrA2sDOrYGnRTIb8TRIxBSDS3mjYjM5xQN1OrQp8f6+cszvkqF24LwHuWox39iYh68pt7uNR4HTgs="
