sudo: false
language: python
matrix:
  include:
    - python: '3.6'
services:
  - mysql
install:
  - pip install flake8 
  - pip install -r requirements.txt
script:
  - flake8 app tests
  - coverage run --source=app test.py
after_sucess:
  - coveralls

