kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: squash-restful-api
  labels:
    app: squash
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: squash
        tier: api
    spec:
      containers:
        - name: nginx
          imagePullPolicy: "Always"
          image: lsstsqre/squash-restful-api-nginx:{{ TAG }}
          lifecycle:
            preStop:
              exec:
                command: ['/usr/sbin/nginx','-s','quit']
          volumeMounts:
            - name: nginx-conf
              mountPath: '/etc/nginx/conf.d'
            - name: tls-certs
              mountPath: '/etc/tls'
        # Flask application
        - name: api
          imagePullPolicy: "Always"
          image: lsstsqre/squash-restful-api:{{ TAG }}
          ports:
            - name: http
              containerPort: 5000
          env:
          - name: SQUASH_DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
          - name: SQUASH_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: password
          - name: SQUASH_API_PROFILE
            value: 'app.config.Production'
          - name: SQUASH_DEFAULT_USER
            value: {{ SQUASH_DEFAULT_USER }}
          - name: SQUASH_DEFAULT_PASSWORD
            value: {{ SQUASH_DEFAULT_PASSWORD }}
          - name: SQUASH_ETL_MODE
            value: {{ SQUASH_ETL_MODE }}
          - name: CELERY_BROKER_URL
            value: 'redis://localhost:6379'
          - name: S3_BUCKET
            value: {{ SQUASH_S3_BUCKET }}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: squash-aws-creds
                key: 'AWS_ACCESS_KEY_ID'
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: squash-aws-creds
                key: 'AWS_SECRET_ACCESS_KEY'
          - name: HONEY_API_KEY
            valueFrom:
              secretKeyRef:
                name: honey-api-key
                key: 'HONEY_API_KEY'
        # Celery worker
        - name: worker
          imagePullPolicy: "Always"
          image: lsstsqre/squash-restful-api:{{ TAG }}
          command: ["celery"]
          args: ["-A", "app.tasks", "-E", "-l", "INFO", "worker"]
          ports:
            - name: http
              containerPort: 5000
          env:
          - name: SQUASH_DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
          - name: SQUASH_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: password
          - name: SQUASH_API_PROFILE
            value: 'app.config.Production'
          - name: SQUASH_DEFAULT_USER
            value: {{ SQUASH_DEFAULT_USER }}
          - name: SQUASH_DEFAULT_PASSWORD
            value: {{ SQUASH_DEFAULT_PASSWORD }}
          - name: SQUASH_ETL_MODE
            value: {{ SQUASH_ETL_MODE }}
          - name: CELERY_BROKER_URL
            value: 'redis://localhost:6379'
          - name: S3_BUCKET
            value: {{ SQUASH_S3_BUCKET }}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: squash-aws-creds
                key: 'AWS_ACCESS_KEY_ID'
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: squash-aws-creds
                key: 'AWS_SECRET_ACCESS_KEY'
        # Broker
        - name: redis
          imagePullPolicy: "Always"
          image: redis
          ports:
            - containerPort: 6379
              name: "redis"
        # https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=plasma-geode-127520:us-central1:{{ INSTANCE_CONNECTION_NAME }}=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: tls-certs
          secret:
            secretName: tls-certs
        - name: nginx-conf
          configMap:
            name: squash-restful-api-nginx-conf
            items:
              - key: 'nginx.conf'
                path: 'nginx.conf'
        # https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
